import type { MongoClient, InsertOneResult, Document, ObjectId, WithId } from 'mongodb'
import { computeOtpHash, type ValidateStatus, type OtpDoc } from './shared'

// Persisted DB shape does NOT store plaintext otp
interface StoredOtpDoc {
  contact: string
  otpHash: string
  createdAt: Date
  _id?: ObjectId
}

export const otpCreate = async (
  client: MongoClient,
  otp: OtpDoc,
): Promise<InsertOneResult<StoredOtpDoc>> => {
  const database = client.db(process.env.MONGO_DATABASE)
  const cursor = database.collection<StoredOtpDoc>(process.env.MONGO_COLLECTION as string)
  if (!otp.createdAt) {
    otp.createdAt = new Date()
  }
  if ('_id' in otp && (otp as any)._id != null) {
    throw new Error('otpCreate does not accept an _id; it will be generated by MongoDB')
  }
  const doc: StoredOtpDoc = {
    contact: otp.contact,
    otpHash: computeOtpHash(otp.contact, otp.otp),
    createdAt: otp.createdAt,
  }
  return await cursor.insertOne(doc)
}

/**
 * Atomically validate and consume OTP, returning a status.
 * - 'ok' when an unexpired matching OTP was found and consumed
 * - 'expired' when a matching OTP existed but is past the TTL (it is deleted)
 * - 'not_found' when no matching OTP exists (wrong/used/TTL-removed)
 */
export const otpValidateWithStatus = async (
  client: MongoClient,
  otp: Pick<OtpDoc, 'contact' | 'otp'>,
  now: Date = new Date(),
  ttlSeconds?: number,
): Promise<ValidateStatus> => {
  const database = client.db(process.env.MONGO_DATABASE)
  const cursor = database.collection<StoredOtpDoc>(process.env.MONGO_COLLECTION as string)
  const otpHash = computeOtpHash(otp.contact, otp.otp)

  // Delete matching doc and retrieve the deleted document for inspection
  const res: any = await cursor.findOneAndDelete({ contact: otp.contact, otpHash } as Document)
  const deleted: WithId<StoredOtpDoc> | null = res && (res.createdAt ? res : (res.value ?? null))

  if (!deleted) return 'not_found'

  const ttl = Number.isFinite(Number(process.env.OTP_EXPIRY)) ? Number(process.env.OTP_EXPIRY) : ttlSeconds
  if (typeof ttl === 'number' && ttl > 0) {
    const createdAt = new Date(deleted.createdAt)
    const ageMs = now.getTime() - createdAt.getTime()
    if (ageMs > ttl * 1000) return 'expired'
  }
  return 'ok'
}

export const otpValidate = async (
  client: MongoClient,
  otp: Pick<OtpDoc, 'contact' | 'otp'>,
): Promise<boolean> => {
  const status = await otpValidateWithStatus(client, otp)
  return status === 'ok'
}
